# Generated by Django 4.2 on 2026-01-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('dept', models.CharField(choices=[('Dev Team', 'Development Team'), ('QA Team', 'Quality Assurance Team'), ('DevOPS Team', 'Deployment Team')], max_length=20)),
                ('role', models.CharField(choices=[('Trainee', 'Trainee Engineer'), ('ASE', 'Associate Software Engineer'), ('ASD', 'Assisstant Software Developer'), ('SSD', 'Senior Software Developer'), ('QA', 'QA Engineer')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
